---
- name: Install nginx
  yum:
    pkg: nginx
    state: present

- name: Replace default nginx configuration to fix duplicate default server error
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Copy nginx configuration for wordpress
  template:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf
  notify: restart nginx

# Handled by role bertvv.el7
#- name: insert firewalld rule for nginx
#  firewalld: port={{ nginx_port }}/tcp permanent=true state=enabled immediate=yes

- name: http service state
  service:
    name: nginx
    state: started
    enabled: yes

- name: Configure SELinux to allow web server to connect to remote database
  seboolean: name=httpd_can_network_connect_db state=true persistent=yes
