---
# Variables for the HAproxy configuration

# HAProxy supports "http" and "tcp". For SSL, SMTP, etc, use "tcp".
mode: tcp

# Port on which HAProxy should listen
listenport: 8888

# A name for the proxy daemon, this wil be the suffix in the logs.
daemonname: blogserver

# Balancing Algorithm. Available options:
# roundrobin, source, leastconn, source, uri
# (if persistence is required use, "source")
balance: roundrobin

# Ethernet interface on which the load balancer should listen
# Defaults to the first interface. Change this to:
#
#  iface: eth1
#
# ...to override.
#
#iface: '{{ ansible_default_ipv4.interface }}'
iface: enp0s8
