---
# This playbook will install MariaDB and create db user and give permissions.

- name: Install MariaDB package
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items:
   - mariadb-server
   - MySQL-python
   - libselinux-python
   - libsemanage-python

- name: Configure SELinux to start mysql on any port
  seboolean:
    name: mysql_connect_any
    state: true
    persistent: yes

- name: Create Mysql configuration file
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  notify:
    - restart mariadb

- name: Create MariaDB log file
  file:
    path: /var/log/mysqld.log
    state: touch
    owner: mysql
    group: mysql
    mode: 0775

- name: Start MariaDB Service
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Create database
  mysql_db:
    name: "{{ mysql_db_name }}"
    state: present

- name: Create database user
  mysql_user:
    name: "{{ mysql_db_user }}"
    password: "{{ mysql_db_password }}"
    priv: "{{ mysql_db_priv }}"
    host: 'localhost'
    state: present

- name: Create remote database user for web1
  mysql_user:
    name: "{{ mysql_db_user }}"
    password: "{{ mysql_db_password }}"
    priv: "{{ mysql_db_priv }}"
    host: "{{ mysql_webserver_name1 }}"
    state: present
- name: Create remote database user for web2
  mysql_user:
    name: "{{ mysql_db_user }}"
    password: "{{ mysql_db_password }}"
    priv: "{{ mysql_db_priv }}"
    host: "{{ mysql_webserver_name2 }}"
    state: present


# Handled by role bertvv.el7. Use el7_firewall_allow_ports instead
#- name: insert firewalld rule
#  firewalld: port={{ mysql_port }}/tcp permanent=true state=enabled immediate=yes
